### ISSUE TITLE
Add GET endpoint to retrieve all tickets

### ISSUE THREAD

**Issue by jonashonecker** [jonashonecker/TicketScout#1]
**Description**
As a user
I want so see all tickets when entering the page.

**To-Do**
- [x] Create a data model for the ticket entitiy
- [x] Write tests for the service and controller methods
- [x] Write a ticket type
- [x] Write a use state on the main page to store tickets (name it `searchResults`)
- [x] Write a TicketCard component to display the search results
- [x] Write a SearchButton Component to trigger the getAll endpoint
