### ISSUE TITLE
Set up CI for main branch

### ISSUE THREAD

**Issue by jonashonecker** [jonashonecker/TicketScout#2]
**Description**
As a developer
when merging to the main branch
the changes should be statically analyzed and
checked whether the new code can be build and
passes all tests.

**To-Do**
- [x] Add Github action for tests and build
- [x] Add static code analysis (sonarcloud)
- [x] Set up automatic prettier check in frontend
- [x] Set up protected main branch (no push)
- [x] Set up Sonar Cloud differently (no new organisation)
- [x] Instead of having multiple yml files being run in parallel, change into one yml file with a chain of jobs: https://blog.maximeheckel.com/posts/building-perfect-github-action-frontend-teams/
