### ISSUE TITLE
Add POST endpoint to create a new ticket

### ISSUE THREAD

**Issue by jonashonecker** [jonashonecker/TicketScout#3]
**Description**
As a user
I want to create new tickets.

**To-Do**
- [x] Create a post endpoint
- [x] write tests for post endpoint
- [x] Write input validation
- [x] Add frontend
- [x] Implement a markdown editor to write a ticket description
