### ISSUE TITLE
Add vector search

### ISSUE THREAD

**Issue by jonashonecker** [jonashonecker/TicketScout#31]
**Description**
As a user
I want to semantically query all tickets
to retrive information easily

**To-Do**
- [x] Extend `tickets` collection to contain new field `title_and_description_embedding`
- [x] On PUT and POST, create embeddings vector of title and description and persist to db
- [x] On GET, create embeddings for string in request body
- [x] Create search index on embedded title and description field
- [x] Write query to search for embedded string upon Get and return values to client
- [x] Implement new GET API request to frontent
- [x] Implement rate limiting for api usage per user

**Sequencediagram**
![Image](https://github.com/jonashonecker/TicketScout/assets/44019407/afc9ed11-3d63-404e-9051-5ce0ad8e4fce)
