### ISSUE TITLE
Add PUT endpoint to update a ticket

### ISSUE THREAD

**Issue by jonashonecker** [jonashonecker/TicketScout#4]
**Description**
As a user
I want to update tickets.

**To-Do**
- [x] Write a put endpoint
- [x] Write tests for put endpoint
- [x] Write a frontend to edit the ticket desription

**Frontend**
- When clicking on a card, the sidepanel opens and the ticket is displayed there
- above the ticket is an edit button which makes the ticket editable
