### ISSUE TITLE
Add Login page

### ISSUE THREAD

**Issue by jonashonecker** [jonashonecker/TicketScout#6]
**Description**
As a user
I want to log in and out of the application to edit my data.

**To-Do**
- [x] Create a log in page to log in via github
- [x] Protect front end routes so they can't be reachend unless logged in
- [x] Protect backend endpoints
- [x] Add a visual that indicates you're logged in
- [x] Add a logout button
- [x] Add tests for backend
